import {LetterState} from "./types"

const kamus =[
    "mario",
    "trian",
    "iqbal",
    "yakob",
    "fahmi",
    "rizza",
    "aling"
]

const initTile = [
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ],
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ],
    [{
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }],
    [{
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }],
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ],
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ]
  ]

export{kamus,initTile}