import {LetterState} from "./types"

const kamus =[
    "abang",
    "bagus",
    "cabai",
    "dadar",
    "edisi",
    "gajah",
    "habis",
    "idola",
    "jabat",
    "kabar",
    "labas",
    "magis",
    "nafsu",
    "obral",
    "pakar",
    "radio",
    "sabar",
    "tabah",
    "udang",
    "valid",
    "wabah",
    "xenia",
    "yakin",
    "zakat",
    "abjad",
    "badak",
    "babak"
]

const initTile = [
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ],
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ],
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ],
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ],
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ],
    [
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      },
      {
        letter:'',
        state:LetterState.INIT
      }
    ]
  ]

const getKatahariIni =()=>{
  const index = Math.floor(Math.random() * kamus.length)
  return kamus[index]
}

export{
  kamus,
  initTile,
  getKatahariIni
}